Task2_CRUD_Web_app/dream-team/app/models.py
# app/models.py

from flask_login import UserMixin
# use some of Werkzeug's handy security helper methods
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager

class Employee(UserMixin, db.Model):
    """
    Create an Employee table
    """

    # Ensures table will be named in plural and not in singular
    # as is the name of the model
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    first_name = db.Column(db.String(60), index=True)
    last_name = db.Column(db.String(60), index=True)
    password_hash = db.Column(db.String(128))
    # two foreign keys refer to the ID's of the department and role
    # assigned to the employee.
    department_id = db.Column(db.Integer, db.ForeignKey('departments.id'))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    is_admin = db.Column(db.Boolean, default=False) # default is False,
                                                    # will override this when creating the admin user

    # enhance security, write a 'password' method which ensures the password can
    # never be accessed, instead an error will be raised
    @property
    def password(self):
        """
        Prevent password from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        # method 'generate_password_hash' allow to hash password
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        # method 'check_password_hash' allow to ensure the hashed password matches the password
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<Employee: {}>'.format(self.username)

    # Set up user_loader callback
    # which Flask-Login uses to reload the user object from the user ID stored in the session
    @login_manager.user_loader
    def load_user(user_id):
        return Employee.query.get(int(user_id))

    class Department(db.Model):
        """
        Create a Department table
        """

        __tablename__ = 'departments'

        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(60), unique=True)
        description = db.Column(db.String(200))
        # The 'Department' model has a one-to-many relationship with the 'Employee' model
        # (one department can have many employees)
        # 'backref' = create a new property on the 'Employee' model such that we can use
        # 'employee.department' to get the department assigned to that employee
        # 'lazy' = how data will be loaded from the database, in this case, it will be
        # loaded dynamically, ideal for managing large collections.
        employees = db.relationship('Employee', backref='department', lazy='dynamic')

        def __repr__(self):
            return '<Department: {}>'.format(self.name)

    class Role(db.Model):
        """
        Create a Role table
        """

        __tablename__ = 'roles'

        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(60), unique=True)
        description = db.Column(db.String(200))
        # The 'Role' model has a one-to-many relationship with the 'Employee' model
        # (one role can have many employees)
        # 'backref' = create a new property on the 'Employee' model such that we can use
        # 'employee.role' to get the role assigned to that employee
        # 'lazy' = how data will be loaded from the database, in this case, it will be
        # loaded dynamically, ideal for managing large collections.
        employees = db.relationship('Employee', backref='role', lazy='dynamic')

        def __repr__(self):
            return '<Role: {}>'.format(self.name)

Task2_CRUD_Web_app/dream-team/app/admin/forms.py
# Forms for admin blueprint

Task2_CRUD_Web_app/dream-team/app/__init__.py
# app/__init__.py

# third-party imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
# after existing third-party imports
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap

# local imports
from config import app_config

# db variable initialization
db = SQLAlchemy()
# after the db variable initialization
login_manager = LoginManager()

def create_app(config_name):
    # given a configuration name, loads the correct configuration from the
    # 'config.py' file, as well as the configuration from the 'instance/config.py' file.
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')

    # create a Bootstrap instance
    Bootstrap(app)
    # create a 'db' object which is used to interact with the database.
    db.init_app(app)

    # # temporary route
    # @app.route('/')
    # def hello_world():
    #     return 'Hello, World!'

    # initialization of the LoginManager object
    login_manager.init_app(app)
    # if a user tries to access a page that they are not authorized to, it will redirect
    # to the specified view and display the specified message
    # not design 'auth.login' view yet
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"

    # create a 'migrate' object which allow to run migrations using Flask-Migrate
    migrate = Migrate(app, db)

    # import the models from the 'app' package
    from app import models

    # register the blueprints on the app
    # import each blueprint object and register it
    from .admin import admin as admin_blueprint
    # for 'admin' blueprint, adding a url prefix
    # meaning all the views for this blueprint will be accessed in the browser with
    # the url prefix '/admin'
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    # import each blueprint object and register it
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    # import each blueprint object and register it
    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

Task2_CRUD_Web_app/dream-team/app/admin/__init__.py
# app/admin/__init__.py

from flask import Blueprint

# create a Blueprint object and initialize it with a name
admin = Blueprint('admin', __name__)

# import the views
from . import views

Task2_CRUD_Web_app/dream-team/app/admin/views.py
# Views for admin blueprint

Task2_CRUD_Web_app/dream-team/app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

# create a Blueprint object and initialize it with a name
home = Blueprint('home', __name__)

# import the views
from . import views

Task2_CRUD_Web_app/dream-team/app/home/views.py
# app/home/views.py

from flask import render_template
from flask_login import login_required

from . import home

# each view function has a decorator, which has a URL route as a parameter
# the homapage view renders the home template
@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title='Welcome')

# the dashboard view renders the dashboard template
# the dashboard view has a decorator, meaning users must be logged in to access it
@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

Task2_CRUD_Web_app/dream-team/app/templates/base.html
<!-- app/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Project Dream Team</title>
    <!-- In the head tag, include link to Font Awesome CSS so we can use icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <!-- Modify nav bar menu -->
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.username }}!</a></li>
      {% else %}
        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
        <li><a href="{{ url_for('auth.register') }}">Register</a></li>
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
      {% endif %}
    </ul>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
      <!-- Modify footer menu -->
      <ul class="list-inline">
          <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
          <li class="footer-menu-divider">⋅</li>
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
            <li class="footer-menu-divider">⋅</li>
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
          {% endif %}
      </ul>
    </footer>
</body>
</html>

Task2_CRUD_Web_app/dream-team/app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>The Dashboard</h1>
                    <h3>We made it here!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Task2_CRUD_Web_app/dream-team/app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Project Dream Team</h1>
                    <h3>The best company in the world!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}